apps/departamentos/urls.py
from django.urls import path
from . import views

app_name='departamento'

urlpatterns = [
    path('', views.DepartamentosList.as_view(), name='list_departamento'),
    path('novo/', views.DepartamentosNew.as_view(), name='novo_departamento'),
    path('editar/<int:pk>/', views.DepartamentosEdit.as_view(), name='editar_departamento'),
    path('deletar/<int:pk>/', views.DepartamentoDelete.as_view(), name='deletar_departamento'),
]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from django.conf.urls import url
from apps.core.views import UserViewSet, GroupViewSet

from apps.funcionarios.api.views import FuncionarioViewSet
from apps.registro_hora_extra.api.views import HoraExtraViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

router.register(r'funcionarios_api', FuncionarioViewSet)
router.register(r'hora_api', HoraExtraViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('funcionarios/', include('apps.funcionarios.urls', namespace='funcionarios')),
    path('funcionarios/documentos/', include('apps.documentos.urls', namespace='documentos')),
    path('funcionarios/horas_extras/', include('apps.registro_hora_extra.urls', namespace='horas_extras')),
    path('departamentos/', include('apps.departamentos.urls', namespace='departamento')),
    path('empresa/', include('apps.empresas.urls', namespace='empresas')),
    path('', include('apps.core.urls', namespace='coracao')),
    path('accounts/', include('django.contrib.auth.urls')),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/departamentos/models.py
from django.db import models
from apps.empresas.models import Empresa


class Departamento(models.Model):
    nome = models.CharField(max_length=100, verbose_name='Nome')
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT)

    def __str__(self):
        return self.nome

apps/departamentos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Departamento

# Create your views here.

class DepartamentosList(ListView):
    model = Departamento

    def get_queryset(self):
        empresa = self.request.user.funcionario.empresa
        return Departamento.objects.filter(empresa=empresa)


class DepartamentosNew(CreateView):
    model = Departamento
    fields = ['nome']
    success_url = '/departamentos/'

    def form_valid(self, form):
        departamento = form.save(commit=False)
        departamento.empresa = self.request.user.funcionario.empresa
        departamento.save()
        return super(DepartamentosNew, self).form_valid(form)


class DepartamentosEdit(UpdateView):
    model = Departamento
    fields = ['nome']
    success_url = '/departamentos/'

class DepartamentoDelete(DeleteView):
    model = Departamento
    success_url = reverse_lazy('departamento:list_departamento')

apps/departamentos/templates/departamentos/departamento_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Deletar Departamento{% endblock %}
{% block main%}

<form method="post">
    {% csrf_token %}
    <h3 class="text-info title">Deseja deletar o departamento {{object}}?</h3>
    <button type="submit" class="btn btn-danger">Deletar</button>
</form>

{% endblock %}

apps/departamentos/templates/departamentos/departamento_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %}Novo Departamento{% endblock %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{form | bootstrap }}
        <button type="submit" class="btn btn-success">Salvar</button>
    </form>
{% endblock %}

apps/departamentos/templates/departamentos/departamento_list.html
{% extends 'base.html' %}
{% block title %}Lista de Departamentos{% endblock %}
{% block main%}
<h3 class="text-info title">Lista de Departamentos</h3>
<hr>
<a href="{% url 'departamento:novo_departamento' %}" class="btn btn-success">Novo Departamento</a>
<hr>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Empresa</th>
        <th scope="col">Editar</th>
        <th scope="col">Deletar</th>
      </tr>
    </thead>
    <tbody>
      {% for departamento in object_list %}
      <tr>
        <th scope="row">{{departamento.id}}</th>
        <td>{{departamento}}</td>
        <td>{{departamento.empresa.nome}}</td>
        <td><a href="{% url 'departamento:editar_departamento' departamento.id %}"
        class="btn btn-info">Editar</a></td>
        <td><a href="{% url 'departamento:deletar_departamento' departamento.id %}"
        class="btn btn-danger">Deletar</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}