apps/documentos/urls.py
from django.urls import path
from . import views

app_name = 'documentos'

urlpatterns = [
    path('novo/', views.DocumentosCreate.as_view(), name='documentocreate'),
    path('deletar/<int:pk>/', views.DocumentosDelete.as_view(), name='documentoDelete'),
    path('editar/<int:pk>/', views.DocumentosEditar.as_view(), name='documentoEditar'),
]

apps/funcionarios/urls.py
from django.urls import path
from . import views

app_name='funcionarios'

urlpatterns = [
    path('edit/<int:pk>/', views.EditarFuncionario.as_view(), name='edit_funcionario'),
    path('delete/<int:pk>/', views.DeletaFuncionario.as_view(), name='delete_funcionario'),
    path('', views.FuncionariosList.as_view(), name='funcionarios_list'),
    path('novo/', views.FuncionariosNovo.as_view(), name='funcionarios_novo'),
    path('pdf-reportlab/', views.some_view, name='pdf-reportlab'),
]

apps/registro_hora_extra/urls.py
from django.urls import path
from . import views

app_name = 'horas_extras'

urlpatterns = [
    path('adicionar/', views.HorasExtrasCreate.as_view(), name='horas_extras-add'),
    path('editar/<int:pk>/', views.HorasExtrasEdit.as_view(), name='horas_extras_edit'),
    path('deletar/<int:pk>/', views.HorasExtrasDelete.as_view(), name='horas_extras_delete'),
]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from django.conf.urls import url
from apps.core.views import UserViewSet, GroupViewSet

from apps.funcionarios.api.views import FuncionarioViewSet
from apps.registro_hora_extra.api.views import HoraExtraViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

router.register(r'funcionarios_api', FuncionarioViewSet)
router.register(r'hora_api', HoraExtraViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('funcionarios/', include('apps.funcionarios.urls', namespace='funcionarios')),
    path('funcionarios/documentos/', include('apps.documentos.urls', namespace='documentos')),
    path('funcionarios/horas_extras/', include('apps.registro_hora_extra.urls', namespace='horas_extras')),
    path('departamentos/', include('apps.departamentos.urls', namespace='departamento')),
    path('empresa/', include('apps.empresas.urls', namespace='empresas')),
    path('', include('apps.core.urls', namespace='coracao')),
    path('accounts/', include('django.contrib.auth.urls')),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from apps.funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(verbose_name='Descrição', max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa

# Create your models here.


class Funcionario(models.Model):
    nome = models.CharField(max_length=100, verbose_name='Nome')
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento, verbose_name='Departamentos')
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return self.nome

    @property
    def total_horas_extras(self):
        total = self.registrohoraextra_set.all().aggregate(Sum('hora_extra'))['hora_extra__sum']
        return total

apps/funcionarios/api/views.py
from rest_framework import viewsets
from apps.funcionarios.api.serializers import FuncionarioSerializer
from apps.funcionarios.models import Funcionario
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication

class FuncionarioViewSet(viewsets.ModelViewSet):
    queryset = Funcionario.objects.all()
    serializer_class = FuncionarioSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

apps/funcionarios/views.py
from django.contrib.auth.models import User
from .form import FuncionarioForm
from django.urls import reverse_lazy
from django.views.generic import (UpdateView,
                                  ListView,
                                  DeleteView,
                                  CreateView)
from .models import Funcionario
import io
from django.http import FileResponse, HttpResponse


class EditarFuncionario(UpdateView):
    model = Funcionario
    form_class = FuncionarioForm
    success_url = '/funcionarios/'

    def get_form_kwargs(self):
        kwargs = super(EditarFuncionario, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa)


class DeletaFuncionario(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('funcionarios:funcionarios_list')


class FuncionariosNovo(CreateView):
    model = Funcionario
    form_class = FuncionarioForm
    template_name = 'funcionarios/novo.html'
    success_url = '/funcionarios/'

    def get_form_kwargs(self):
        kwargs = super(FuncionariosNovo, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


    def form_valid(self, form):
        funcionario = form.save(commit=False)
        usuario = funcionario.nome.split(' ')[0]
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create_user(username=usuario)
        return super(FuncionariosNovo, self).form_valid(form)


def some_view(request):
    response = HttpResponse(content_type='aplication/pdf')
    response['Content-Disposition'] = 'attachment; filename="mypdf.pdf'

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)

    p.drawString(10, 810, 'Hello World!')

    palavras = ['palavra1', 'palavra2', 'pallavra3']

    y=790

    for palavra in palavras:
        p.drawString(10, y, palavra)
        y -= 40

    p.showPage()
    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    return response

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Deletar Funcionários{% endblock %}
{% block main%}

<form method="post">
    {% csrf_token %}
    <h3 class="text-info title">Deseja deletar  {{object}}?</h3>
    <button type="submit" class="btn btn-danger">Deletar</button>
</form>

{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %}Editar Funcionário{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-4">
            <h3 class="text-info title">Perfil Funionário</h3>
        <form method="post">
        {% csrf_token %}
        {{form | bootstrap }}
        <button type="submit" class="btn btn-block btn-success">Salvar</button>
        </form>
            <hr>
        </div>
        <div class="col-md-8">
            <h3 class="text-info title">Documentos</h3>
            <table class="table">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">Descrição</th>
                    <th scope="col">Visualizar</th>
                    <th scope="col">Editar</th>
                    <th scope="col">Deletar</th>
                  </tr>
                </thead>
                <tbody>
                  {% for documento in object.documento_set.all %}
                  <tr>
                    <td>{{documento}}</td>
                    <td><a href="{{documento.arquivo.url}}">Visualizar</a></td>
                    <td><a href="{% url 'documentos:documentoEditar' documento.pk %}"
                    class="btn btn-info">Editar</a></td>
                    <td><a href="{% url 'documentos:documentoDelete' documento.pk %}"
                    class="btn btn-danger">Deletar</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              <hr>
              <a href="{% url 'documentos:documentocreate' %}" class="btn btn-block btn-info">Adicionar documento</a><br>
              <hr>

            <h3 class="text-info title">Banco de Horas</h3>
            <table class="table">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">Motivo</th>
                    <th scope="col">Hora_Extra</th>
                    <th scope="col">Editar</th>
                    <th scope="col">Deletar</th>
                  </tr>
                </thead>
                <tbody>
                  {% for hora in object.registrohoraextra_set.all %}
                  <tr>
                    <td>{{hora}}</td>
                    <td>{{hora.hora_extra}}</td>
                    <td><a href="{% url 'horas_extras:horas_extras_edit' hora.pk %}"
                    class="btn btn-info">Editar</a></td>
                    <td><a href="{% url 'horas_extras:horas_extras_delete' hora.pk %}"
                    class="btn btn-danger">Deletar</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            <br>
                <h5 class="text-info title">Total Horas: {{object.total_horas_extras}}</h5>
            <hr>
            <a href="{% url 'horas_extras:horas_extras-add' %}" class="btn btn-block btn-info">Registrar Hora Extra</a>
        </div>
    </div>
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}
{% block title %}Lista de Funcionários{% endblock %}
{% block main%}
<h3 class="text-info title">Lista de Funcionários</h3>
<hr>
<a href="{% url 'funcionarios:funcionarios_novo' %}" class="btn btn-success">Novo Funcionario</a>
<a href="{% url 'funcionarios:pdf-reportlab' %}" class="btn btn-info">Pdf Reportlab</a>
<hr>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Empresa</th>
        <th scope="col">Editar</th>
        <th scope="col">Deletar</th>
      </tr>
    </thead>
    <tbody>
      {% for funcionario in object_list %}
      <tr>
        <th scope="row">{{funcionario.id}}</th>
        <td>{{funcionario}}</td>
        <td>{{funcionario.empresa.nome}}</td>
        <td><a href="{% url 'funcionarios:edit_funcionario' funcionario.pk %}"
        class="btn btn-info">Editar</a></td>
        <td><a href="{% url 'funcionarios:delete_funcionario' funcionario.pk %}"
        class="btn btn-danger">Deletar</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

apps/funcionarios/templates/funcionarios/novo.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %}Novo Funcionário{% endblock %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{form | bootstrap }}
        <button type="submit" class="btn btn-success">Cadastrar</button>
    </form>
{% endblock %}