apps/core/urls.py
from django.urls import path

from . import views

app_name = 'coracao'



urlpatterns = [
    path('', views.home, name='index'),
    path('sair/', views.sair, name='sair'),
]

apps/departamentos/urls.py
from django.urls import path
from . import views

app_name='departamento'

urlpatterns = [
    path('', views.DepartamentosList.as_view(), name='list_departamento'),
    path('novo/', views.DepartamentosNew.as_view(), name='novo_departamento'),
    path('editar/<int:pk>/', views.DepartamentosEdit.as_view(), name='editar_departamento'),
    path('deletar/<int:pk>/', views.DepartamentoDelete.as_view(), name='deletar_departamento'),
]

apps/empresas/urls.py
from django.urls import path
from . import views

app_name = 'empresas'

urlpatterns = [
    path('nova/', views.CriarEmpresa.as_view(), name='criar_empresa'),
    path('editar/<int:pk>/', views.EditarEmpresa.as_view(), name='editar_empresa'),
]

apps/funcionarios/urls.py
from django.urls import path
from . import views

app_name='funcionarios'

urlpatterns = [
    path('edit/<int:pk>/', views.EditarFuncionario.as_view(), name='edit_funcionario'),
    path('delete/<int:pk>/', views.DeletaFuncionario.as_view(), name='delete_funcionario'),
    path('', views.FuncionariosList.as_view(), name='funcionarios_list'),
    path('novo/', views.FuncionariosNovo.as_view(), name='funcionarios_novo'),
    path('pdf-reportlab/', views.some_view, name='pdf-reportlab'),
]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from django.conf.urls import url
from apps.core.views import UserViewSet, GroupViewSet

from apps.funcionarios.api.views import FuncionarioViewSet
from apps.registro_hora_extra.api.views import HoraExtraViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

router.register(r'funcionarios_api', FuncionarioViewSet)
router.register(r'hora_api', HoraExtraViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('funcionarios/', include('apps.funcionarios.urls', namespace='funcionarios')),
    path('funcionarios/documentos/', include('apps.documentos.urls', namespace='documentos')),
    path('funcionarios/horas_extras/', include('apps.registro_hora_extra.urls', namespace='horas_extras')),
    path('departamentos/', include('apps.departamentos.urls', namespace='departamento')),
    path('empresa/', include('apps.empresas.urls', namespace='empresas')),
    path('', include('apps.core.urls', namespace='coracao')),
    path('accounts/', include('django.contrib.auth.urls')),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

# Create your models here.

apps/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from apps.core.serializers import UserSerializer, GroupSerializer

# Create your views here.

@login_required
def home(request):
    usuario = request.user
    contexto = {'usuario':usuario}
    return render(request, 'core/home.html', contexto)


def sair(request):
    return render(request, 'core/logout.html')

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    queryset = Group.objects.all().order_by()
    serializer_class = GroupSerializer

apps/core/templates/core/home.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inicio</title>
    <meta name="author" content="name">
    <meta name="description" content="description here">
    <meta name="keywords" content="keywords,here">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet"> <!--Replace with your tailwind.css once created-->
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet"> <!--Totally optional :) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js" integrity="sha256-xKeoJ50pzbUGkpQxDYHD7o7hxe0LaOGeguUidbq6vis=" crossorigin="anonymous"></script>

</head>

<body class="bg-gray-900 font-sans leading-normal tracking-normal mt-12">

    <!--Nav-->
    <nav class="bg-gray-900 pt-2 md:pt-1 pb-1 px-1 mt-0 h-auto fixed w-full z-20 top-0">

        <div class="flex flex-wrap items-center">
            <div class="flex flex-shrink md:w-1/3 justify-center md:justify-start text-white">
                <a href="#">
                    <span class="text-xl pl-2"><i class="em em-grinning"></i></span>
                </a>
            </div>

            <div class="flex flex-1 md:w-1/3 justify-center md:justify-start text-white px-2">
                <span class="relative w-full">
                    <input type="search" placeholder="Procurar" class="w-full bg-gray-800 text-sm text-white transition border border-transparent focus:outline-none focus:border-gray-700 rounded py-1 px-2 pl-10 appearance-none leading-normal">
                    <div class="absolute search-icon" style="top: .5rem; left: .8rem;">
                        <svg class="fill-current pointer-events-none text-white w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                            <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
                        </svg>
                    </div>
                </span>
			</div>

			<div class="flex w-full pt-2 content-center justify-between md:w-1/3 md:justify-end">
				<ul class="list-reset flex justify-between flex-1 md:flex-none items-center">
				    <li class="flex-1 md:flex-none md:mr-3">
					    <a class="inline-block py-2 px-4 text-white no-underline" href="#">Active</a>
				    </li>
				    <li class="flex-1 md:flex-none md:mr-3">
					    <a class="inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4" href="{% url 'funcionarios:edit_funcionario' usuario.funcionario.id %}">Editar</a>
				    </li>
				    <li class="flex-1 md:flex-none md:mr-3">
						<div class="relative inline-block">
							<button onclick="toggleDD('myDropdown')" class="drop-button text-white focus:outline-none"> <span class="pr-2"><i class="em em-robot_face"></i></span> Olá {{user}} <svg class="h-3 fill-current inline" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg></button>
                            <div id="myDropdown" class="dropdownlist absolute bg-gray-900 text-white right-0 mt-3 p-3 overflow-auto z-30 invisible">
                                <input type="text" class="drop-search p-2 text-gray-600" placeholder="Procurar.." id="myInput" onkeyup="filterDD('myDropdown','myInput')">
                                <a href="#" class="p-2 hover:bg-gray-800 text-white text-sm no-underline hover:no-underline block"><i class="fa fa-user fa-fw"></i> Perfil</a>
                                <a href="#" class="p-2 hover:bg-gray-800 text-white text-sm no-underline hover:no-underline block"><i class="fa fa-cog fa-fw"></i> Configurações</a>
                                <div class="border border-gray-800"></div>
                                <a href="{% url 'logout' %}" class="p-2 hover:bg-gray-800 text-white text-sm no-underline hover:no-underline block"><i class="fas fa-sign-out-alt fa-fw"></i> Logout</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

    </nav>


    <div class="flex flex-col md:flex-row">

        <div class="bg-gray-900 shadow-lg h-16 fixed bottom-0 mt-12 md:relative md:h-screen z-10 w-full md:w-48">

            <div class="md:mt-12 md:w-48 md:fixed md:left-0 md:top-0 content-center md:content-start text-left justify-between">
                <ul class="list-reset flex flex-row md:flex-col py-0 md:py-3 px-1 md:px-2 text-center md:text-left">
                    <li class="mr-3 flex-1">
                        <a href="#" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-pink-500">
                            <i class="fas fa-tasks pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block">Tarefas</span>
                        </a>
                    </li>
                    <li class="mr-3 flex-1">
                        <a href="#" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-purple-500">
                            <i class="fa fa-envelope pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block">Mensagens</span>
                        </a>
                    </li>
                    <li class="mr-3 flex-1">
                        <a href="#" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-blue-600">
                            <i class="fas fa-chart-area pr-0 md:pr-3 text-blue-600"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-white md:text-white block md:inline-block">Analises</span>
                        </a>
                    </li>
                    <li class="mr-3 flex-1">
                        <a href="#" class="block py-1 md:py-3 pl-0 md:pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-800 hover:border-red-500">
                            <i class="fa fa-wallet pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block">Pagamentos</span>
                        </a>
                    </li>
                </ul>
            </div>


        </div>

        <div class="main-content flex-1 bg-gray-100 mt-12 md:mt-2 pb-24 md:pb-5">

            <div class="bg-blue-800 p-2 shadow text-xl text-white">
                <h3 class="font-bold pl-2">Painel administrativo</h3>
            </div>

            <div class="flex flex-wrap">
                {% if usuario.funcionario.empresa %}
                <div class="w-full md:w-1/2 xl:w-1/2 p-3">
                    <!--Metric Card-->
                    <div class="bg-yellow-100 border-b-4 border-yellow-600 rounded-lg shadow-lg p-5">
                        <div class="flex flex-row items-center">
                            <div class="flex-shrink pr-4">
                                <div class="rounded-full p-5 bg-yellow-600"><i class="fas fa-user fa-2x fa-inverse"></i></div>
                            </div>
                            <div class="flex-1 text-right md:text-center">
                                <a href="{% url 'funcionarios:funcionarios_list' %}"
                                   class="font-bold uppercase text-gray-600">Funcionários</a>
                             </div>
                        </div>
                    </div>
                    <!--/Metric Card-->
                </div>

                <div class="w-full md:w-1/2 xl:w-1/2 p-3">
                    <!--Metric Card-->
                    <div class="bg-red-100 border-b-4 border-red-500 rounded-lg shadow-lg p-5">
                        <div class="flex flex-row items-center">
                            <div class="flex-shrink pr-4">
                                <div class="rounded-full p-5 bg-red-600"><i class="fas fa-inbox fa-2x fa-inverse"></i></div>
                            </div>
                            <div class="flex-1 text-right md:text-center">
                                <a href="{% url 'empresas:editar_empresa' usuario.funcionario.empresa.pk %}"
                                   class="font-bold uppercase text-gray-600">{{usuario.funcionario.empresa}}</a>
                            </div>
                        </div>
                    </div>
                    <!--/Metric Card-->
                </div>

                <div class="w-full md:w-1/2 xl:w-1/3 p-3">
                    <!--Metric Card-->
                    <div class="bg-blue-100 border-b-4 border-blue-500 rounded-lg shadow-lg p-5">
                        <div class="flex flex-row items-center">
                            <div class="flex-shrink pr-4">
                                <div class="rounded-full p-5 bg-blue-600"><i class="fas fa-server fa-2x fa-inverse"></i></div>
                            </div>
                            <div class="flex-1 text-right md:text-center">
                                <a href="{% url 'departamento:list_departamento' %}" class="font-bold uppercase text-gray-600">Departamentos</a>
                            </div>
                        </div>
                    </div>
                    <!--/Metric Card-->
                </div>

                <div class="w-full md:w-1/2 xl:w-1/3 p-3">
                    <!--Metric Card-->
                    <div class="bg-green-100 border-b-4 border-green-600 rounded-lg shadow-lg p-5">
                        <div class="flex flex-row items-center">
                            <div class="flex-shrink pr-4">
                                <div class="rounded-full p-5 bg-green-600"><i class="fa fa-wallet fa-2x fa-inverse"></i></div>
                            </div>
                            <div class="flex-1 text-right md:text-center">
                                <h5 class="font-bold uppercase text-gray-600">Documentos</h5>
                            </div>
                        </div>
                    </div>
                    <!--/Metric Card-->
                </div>

                <div class="w-full md:w-1/2 xl:w-1/3 p-3">
                    <!--Metric Card-->
                    <div class="bg-indigo-100 border-b-4 border-indigo-500 rounded-lg shadow-lg p-5">
                        <div class="flex flex-row items-center">
                            <div class="flex-shrink pr-4">
                                <div class="rounded-full p-5 bg-indigo-600"><i class="fas fa-tasks fa-2x fa-inverse"></i></div>
                            </div>
                            <div class="flex-1 text-right md:text-center">
                                <a href="#" class="font-bold uppercase text-gray-600">Horas Extras</a>
                            </div>
                        </div>
                    </div>
                    <!--/Metric Card-->
                </div>
                {% else %}
                <div class="w-full md:w-1/2 xl:w-1/3 p-3">

                    <div class="bg-orange-100 border-b-4 border-orange-500 rounded-lg shadow-lg p-5">
                        <div class="flex flex-row items-center">
                            <div class="flex-shrink pr-4">
                                <div class="rounded-full p-5 bg-orange-600"><i class="fas fa-users fa-2x fa-inverse"></i></div>
                            </div>
                            <div class="flex-1 text-right md:text-center">
                                <a href="{% url 'empresas:criar_empresa' %}" class="font-bold uppercase text-gray-600">Criar Empresa</a>
                                <!--Metric Card
                                <h3 class="font-bold text-3xl">249 <span class="text-orange-500"><i class="fas fa-exchange-alt"></i></span></h3>
                                -->
                            </div>
                        </div>
                    </div>
                    <!--/Metric Card-->
                </div>
                {% endif %}
            </div>

        </div>
    </div>

    <script>
        /*Toggle dropdown list*/
        function toggleDD(myDropMenu) {
            document.getElementById(myDropMenu).classList.toggle("invisible");
        }
        /*Filter dropdown options*/
        function filterDD(myDropMenu, myDropMenuSearch) {
            var input, filter, ul, li, a, i;
            input = document.getElementById(myDropMenuSearch);
            filter = input.value.toUpperCase();
            div = document.getElementById(myDropMenu);
            a = div.getElementsByTagName("a");
            for (i = 0; i < a.length; i++) {
                if (a[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
                    a[i].style.display = "";
                } else {
                    a[i].style.display = "none";
                }
            }
        }
        // Close the dropdown menu if the user clicks outside of it
        window.onclick = function(event) {
            if (!event.target.matches('.drop-button') && !event.target.matches('.drop-search')) {
                var dropdowns = document.getElementsByClassName("dropdownlist");
                for (var i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (!openDropdown.classList.contains('invisible')) {
                        openDropdown.classList.add('invisible');
                    }
                }
            }
        }
    </script>


</body>

</html>

apps/core/templates/core/index.html
{% extends 'base.html' %}
{% block title %}
Seja Bem Vindo!
{% endblock %}
{% block main %}
    <div class="row">
        <div class="col-sm-4">
            <h3 class="title text-info">Olá {{user}}</h3>
        </div>
        <div class="col-sm-4">
            {% if usuario.funcionario.empresa %}
            <h3 class="title text-info">{{usuario.funcionario.empresa}}</h3>
            <a href="{% url 'empresas:editar_empresa' usuario.funcionario.empresa.pk %}">Editar Empresa</a>
            <h3 class="title text-info">Funcionários</h3>
            <a href="{% url 'funcionarios:funcionarios_list' %}">Lista de Funcionários</a>
            <h3 class="title text-info">Departamentos</h3>
            <a href="{% url 'departamento:list_departamento' %}">Lista de Departamentos</a>
            <h3 class="title text-info">Horas Extras</h3>
            <a href="{% url 'horas_extras:horas_extras-lista' %}">Lista de Horas Extras</a>
            {% else %}
            <a href="{% url 'empresas:criar_empresa' %}">Criar Empresa</a>
            {% endif %}
        </div>
        <div class="col-sm-4">
            <h3 class="title text-info">Ação</h3>
            <a href="{% url 'logout' %}" class="btn btn-warning">Sair</a><br><br>
            <a href="{% url 'funcionarios:edit_funcionario' usuario.funcionario.id %}"
               class="btn btn-info">Editar Funcionário</a>
        </div>
    </div>
{% endblock %}

apps/core/templates/core/logout.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block main %}
    <hr>
    <div class="row">
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
            <a href="{% url 'login' %}" class="btn btn-danger">Entrar Novamente</a>
        </div>
        <div class="col-sm-4">
        </div>
    </div>

{% endblock %}